const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Behaviors.MoveTo,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Behaviors.Pin,
		C3.Behaviors.Tween,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Arr,
		C3.Plugins.AJAX,
		C3.Behaviors.scrollto,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.advert,
		C3.Plugins.CORDOVAIAP,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.PickTopBottom,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.ToggleBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Behaviors.DragnDrop.Cnds.IsEnabled,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.PickOverlappingPoint,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.System.Exps.rgba255,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Behaviors.MoveTo.Acts.Stop,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.MoveTo.Acts.SetEnabled,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Text.Acts.AddInstanceVar,
		C3.Plugins.Text.Acts.SetBoolInstanceVar,
		C3.Plugins.Text.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.SetEnabled,
		C3.Plugins.Mouse.Acts.SetCursor
	];
};
self.C3_JsPropNameTable = [
	{КузницаСлот: 0},
	{ValueP1: 0},
	{p1: 0},
	{ValueP10: 0},
	{p10: 0},
	{ValueP11: 0},
	{p11: 0},
	{ValueP12: 0},
	{p12: 0},
	{ValueP13: 0},
	{Конец: 0},
	{p13: 0},
	{ValueP14: 0},
	{p14: 0},
	{ValueP15: 0},
	{p15: 0},
	{ValueP16: 0},
	{p16: 0},
	{ValueP2: 0},
	{p2: 0},
	{ValueP3: 0},
	{p3: 0},
	{ValueP4: 0},
	{p4: 0},
	{ValueP5: 0},
	{p5: 0},
	{ValueP6: 0},
	{p6: 0},
	{ValueP7: 0},
	{p7: 0},
	{ValueP8: 0},
	{p8: 0},
	{ValueP9: 0},
	{p9: 0},
	{Value: 0},
	{Spawn1: 0},
	{Spawn2: 0},
	{Spawn3: 0},
	{Spawn4: 0},
	{АппаратПеред: 0},
	{ТайловыйФон: 0},
	{АппаратЗад: 0},
	{Рычаг: 0},
	{Спрайт4: 0},
	{Дракон: 0},
	{Двигается: 0},
	{Созданная: 0},
	{ДвижениеК: 0},
	{Твердый: 0},
	{монетаНоль: 0},
	{Клавиатура: 0},
	{Destroy: 0},
	{монетаПлюс: 0},
	{монета8: 0},
	{Прогресс: 0},
	{монета12: 0},
	{монета2: 0},
	{монета16: 0},
	{Жрут: 0},
	{Спрайт5: 0},
	{Bank: 0},
	{БАНК: 0},
	{Спрайт6: 0},
	{фоноснова: 0},
	{Звяки: 0},
	{Коммунити: 0},
	{Мышь: 0},
	{Сияние: 0},
	{Исчезание: 0},
	{Крепость: 0},
	{Анимация: 0},
	{СпавнТригера: 0},
	{Обвал: 0},
	{ИнвРабочий: 0},
	{ИнвДинамит: 0},
	{ИнвКислота: 0},
	{ВКЛ: 0},
	{КнопкаМагазин: 0},
	{КнопкаСундук: 0},
	{КнопкаКомм: 0},
	{Что: 0},
	{фон: 0},
	{Фонкоммунити: 0},
	{Прикрепить: 0},
	{Рабочие: 0},
	{Золото: 0},
	{Донат: 0},
	{Тень: 0},
	{ЗнакРабочий: 0},
	{ТехнНоль: 0},
	{ФонСундук: 0},
	{Открытие: 0},
	{Сундук: 0},
	{Спрайт: 0},
	{Ключ: 0},
	{Твинанимация: 0},
	{КлючОдин: 0},
	{ЗнакСундук: 0},
	{Фонмагазин: 0},
	{магазинфон: 0},
	{Сундук3: 0},
	{торговец: 0},
	{Стол: 0},
	{ДинамитМагазин: 0},
	{Склянкамагазин: 0},
	{Знакмагазин: 0},
	{ТАЧ: 0},
	{СундукЗначок: 0},
	{МагазинЗначок: 0},
	{Спрайт2: 0},
	{ДРАКОН: 0},
	{Д: 0},
	{Угли: 0},
	{Спрайт3: 0},
	{ГораЗолота: 0},
	{Перетаскивание: 0},
	{Рабочий: 0},
	{Склянка: 0},
	{Динамит: 0},
	{Цена: 0},
	{Разъедание: 0},
	{Взрыв: 0},
	{Удары: 0},
	{НетЗолота: 0},
	{Валуе: 0},
	{КиркаДолбит: 0},
	{маскаЗолота: 0},
	{КоличествоКлючей: 0},
	{Лут: 0},
	{Лутбокс: 0},
	{ПлюсГолда: 0},
	{Спрайт7: 0},
	{Спрайт8: 0},
	{ФонКнопок: 0},
	{Слова: 0},
	{AJAX: 0},
	{Гномы: 0},
	{Гоблины: 0},
	{ФонДиалог: 0},
	{CopX: 0},
	{CopY: 0},
	{СловаТекст: 0},
	{ТехнДиалог: 0},
	{Д2: 0},
	{Биржа: 0},
	{СледитьЗа: 0},
	{Камера: 0},
	{Экран1: 0},
	{Экран2: 0},
	{БиржаМеню: 0},
	{Спрайт9: 0},
	{КнопкаКрасная: 0},
	{КнопкаЗеленая: 0},
	{Худ1: 0},
	{Спот1: 0},
	{ФонБиржа: 0},
	{СтрелкаНазад: 0},
	{Текст: 0},
	{Купить: 0},
	{Продать: 0},
	{ТекстБиржа: 0},
	{Спрайт10: 0},
	{ВашСчет: 0},
	{ВашБаланс: 0},
	{ЦенаАкции: 0},
	{фонпотеря: 0},
	{Потеря: 0},
	{Потеря2: 0},
	{ЦенаАкции2: 0},
	{потеряспот: 0},
	{ВашБаланс2: 0},
	{ЗолотоедСпавн: 0},
	{Золотоед: 0},
	{Спрайт11: 0},
	{Свет: 0},
	{Свет1: 0},
	{Переключение: 0},
	{ОбучалкаНачало: 0},
	{Договор: 0},
	{стрелкааним: 0},
	{Позиция: 0},
	{Начало: 0},
	{ДоговорБольшой: 0},
	{Обводыч: 0},
	{Стрелок: 0},
	{ОбучалкаКлик: 0},
	{обводкаинвентаря: 0},
	{Появление: 0},
	{ОблачкоНетЗолота: 0},
	{ОблачкоНетЗолота2: 0},
	{ОписаниеПредметов: 0},
	{Спрайт12: 0},
	{Спрайт13: 0},
	{обводкаинвентаря2: 0},
	{обводкаинвентаря3: 0},
	{КоличествоДинамита: 0},
	{КоличествоСклянок: 0},
	{Спавн: 0},
	{Монета: 0},
	{КузницаПеред: 0},
	{КузницаЗад: 0},
	{Купить3: 0},
	{Купить4: 0},
	{Купить5: 0},
	{Подписан: 0},
	{Подпись: 0},
	{ПОБЕДА: 0},
	{СветПобеда: 0},
	{ПОБЕДА2: 0},
	{Движение: 0},
	{Ура: 0},
	{Проигрыш: 0},
	{мешок: 0},
	{Спрайт15: 0},
	{Спрайт16: 0},
	{ТайловыйФон2: 0},
	{Теньмешок: 0},
	{ТайловыйФон3: 0},
	{Экран3: 0},
	{ФонМеню: 0},
	{Спрайт17: 0},
	{НазваниеИгры: 0},
	{Спрайт19: 0},
	{Язык: 0},
	{Музыка: 0},
	{Звук: 0},
	{КнопкаИстория: 0},
	{КнопкаСвободнаяИстория: 0},
	{НазадСменю: 0},
	{Руки1: 0},
	{Руки2: 0},
	{Руки3: 0},
	{Блекскрин: 0},
	{Спрайт14: 0},
	{Заного: 0},
	{ТриПолоски: 0},
	{Кнопка1: 0},
	{Кнопка2: 0},
	{Кнопка3: 0},
	{Кнопка4: 0},
	{КнопкаТехн: 0},
	{Текст2: 0},
	{КнопкиМенюТекст: 0},
	{ЛокальноеХранилище: 0},
	{Удалить: 0},
	{Аудио: 0},
	{Спрайт18: 0},
	{Тач2: 0},
	{Гномик: 0},
	{Цвет: 0},
	{Квесты: 0},
	{Прокачка: 0},
	{Прокачка2: 0},
	{КлючРеклама: 0},
	{МобильнаяРеклама: 0},
	{Палец: 0},
	{Управлятор: 0},
	{Светок: 0},
	{ВзрывТриггер: 0},
	{Рука: 0},
	{РукаПоинт1: 0},
	{РукаПоинт2: 0},
	{Обучалка: 0},
	{Спрайт20: 0},
	{Спрайт21: 0},
	{ПокупкиВПриложенияхIAP: 0},
	{ДвижениеК2: 0},
	{Монеты: 0},
	{ХУД: 0},
	{Диалог: 0},
	{Поинтс: 0},
	{Кнопки: 0},
	{КузницаСлоты: 0},
	{КнопкиЯзык: 0},
	{КнопкиМеню: 0},
	{НеТач: 0},
	{НеМеню: 0},
	{Empty1: 0},
	{Empty2: 0},
	{Empty3: 0},
	{Empty4: 0},
	{VolueP1: 0},
	{VolueP2: 0},
	{VolueP3: 0},
	{VolueP4: 0},
	{VolueP5: 0},
	{VolueP6: 0},
	{ЯЗЫК: 0},
	{VolueP7: 0},
	{VolueP8: 0},
	{VolueP9: 0},
	{МонетыОбучалка: 0},
	{VolueP10: 0},
	{VolueP11: 0},
	{VolueP12: 0},
	{VolueP13: 0},
	{VolueP14: 0},
	{VolueP15: 0},
	{VolueP16: 0},
	{VolueN1: 0},
	{VolueN2: 0},
	{VolueN3: 0},
	{VolueN4: 0},
	{VolueN5: 0},
	{VolueN6: 0},
	{VolueN7: 0},
	{VolueN8: 0},
	{VolueN9: 0},
	{VolueN10: 0},
	{VolueN11: 0},
	{ДраконОбучение: 0},
	{VolueN12: 0},
	{VolueN13: 0},
	{VolueN14: 0},
	{VolueN15: 0},
	{VolueN16: 0},
	{VolueD1: 0},
	{VolueD2: 0},
	{VolueD3: 0},
	{VolueD4: 0},
	{VolueD5: 0},
	{VolueD6: 0},
	{VolueD7: 0},
	{VolueD8: 0},
	{ЗолотоедОбучение: 0},
	{VolueD9: 0},
	{VolueD10: 0},
	{VolueD11: 0},
	{VolueD12: 0},
	{VolueD13: 0},
	{VolueD14: 0},
	{VolueD15: 0},
	{VolueD16: 0},
	{VolueE1: 0},
	{VolueE2: 0},
	{VolueE3: 0},
	{VolueE4: 0},
	{VolueE5: 0},
	{VolueE6: 0},
	{VolueE7: 0},
	{VolueE8: 0},
	{VolueE9: 0},
	{VolueE10: 0},
	{VolueE11: 0},
	{VolueE12: 0},
	{VolueE13: 0},
	{VolueE14: 0},
	{VolueE15: 0},
	{VolueE16: 0},
	{ПлатаОбучение: 0},
	{ValueSpawn: 0},
	{ЦенаСдвига: 0},
	{КРЕПОСТЬУГЛЕЙ: 0},
	{Скам: 0},
	{ЦенаБилета: 0},
	{Баланс: 0},
	{Билеты: 0},
	{Занос: 0},
	{ЗолотоедыСложность: 0},
	{ЗолотоедыСпавн: 0},
	{ЗолотоедыКоличество: 0},
	{ВесьБаланс: 0},
	{МонетыНачало: 0},
	{ПозицияДоговора: 0},
	{Долг: 0},
	{ДнейДоВыплаты: 0},
	{ДоговорОбучалка: 0},
	{ВпервыйРаз: 0},
	{СтрелкаАнимМеню: 0},
	{СундукОбучалка: 0},
	{История: 0},
	{Игра: 0},
	{ПРОВЕРКА: 0},
	{ДраконЕсть: 0},
	{ТачНачалоХ: 0},
	{ТачНачалоУ: 0},
	{ТачКонецХ: 0},
	{ТачКонецУ: 0},
	{ДвижГоризонталь: 0},
	{ДвижВертикаль: 0},
	{ТачРазницаХ: 0},
	{ТачРазницаУ: 0},
	{Меню: 0},
	{ЦенаПрокачки: 0},
	{Множитель: 0},
	{ЦенаДинамит: 0},
	{ЦенаСклянка: 0},
	{ДонатОбучалка: 0},
	{КопилкаГоблинов: 0},
	{ДонатКлики: 0},
	{Ключи: 0},
	{КузницаОбучалка: 0},
	{Победа: 0},
	{Поражение: 0},
	{ЯзыкПобеда: 0},
	{ПоражениеАппарат: 0},
	{МузыкаГромкость: 0},
	{ГромкостьЗвук: 0},
	{МузыкаМьют: 0}
];

self.InstanceType = {
	p1: class extends self.ISpriteInstance {},
	p10: class extends self.ISpriteInstance {},
	p11: class extends self.ISpriteInstance {},
	p12: class extends self.ISpriteInstance {},
	p13: class extends self.ISpriteInstance {},
	p14: class extends self.ISpriteInstance {},
	p15: class extends self.ISpriteInstance {},
	p16: class extends self.ISpriteInstance {},
	p2: class extends self.ISpriteInstance {},
	p3: class extends self.ISpriteInstance {},
	p4: class extends self.ISpriteInstance {},
	p5: class extends self.ISpriteInstance {},
	p6: class extends self.ISpriteInstance {},
	p7: class extends self.ISpriteInstance {},
	p8: class extends self.ISpriteInstance {},
	p9: class extends self.ISpriteInstance {},
	Spawn1: class extends self.ISpriteInstance {},
	Spawn2: class extends self.ISpriteInstance {},
	Spawn3: class extends self.ISpriteInstance {},
	Spawn4: class extends self.ISpriteInstance {},
	АппаратПеред: class extends self.ISpriteInstance {},
	ТайловыйФон: class extends self.ITiledBackgroundInstance {},
	АппаратЗад: class extends self.ISpriteInstance {},
	Рычаг: class extends self.ISpriteInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	монетаНоль: class extends self.ISpriteInstance {},
	Клавиатура: class extends self.IInstance {},
	монетаПлюс: class extends self.ISpriteInstance {},
	монета8: class extends self.ISpriteInstance {},
	монета12: class extends self.ISpriteInstance {},
	монета2: class extends self.ISpriteInstance {},
	монета16: class extends self.ISpriteInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	БАНК: class extends self.ITextInstance {},
	Спрайт6: class extends self.ISpriteInstance {},
	фоноснова: class extends self.ISpriteInstance {},
	Коммунити: class extends self.ISpriteInstance {},
	Мышь: class extends self.IInstance {},
	Сияние: class extends self.ISpriteInstance {},
	Исчезание: class extends self.ISpriteInstance {},
	Обвал: class extends self.ISpriteInstance {},
	ИнвРабочий: class extends self.ISpriteInstance {},
	ИнвДинамит: class extends self.ISpriteInstance {},
	ИнвКислота: class extends self.ISpriteInstance {},
	КнопкаМагазин: class extends self.ISpriteInstance {},
	КнопкаСундук: class extends self.ISpriteInstance {},
	КнопкаКомм: class extends self.ISpriteInstance {},
	фон: class extends self.ISpriteInstance {},
	Фонкоммунити: class extends self.ISpriteInstance {},
	Рабочие: class extends self.ISpriteInstance {},
	Золото: class extends self.ISpriteInstance {},
	Донат: class extends self.ISpriteInstance {},
	Тень: class extends self.ISpriteInstance {},
	ЗнакРабочий: class extends self.ISpriteInstance {},
	ТехнНоль: class extends self.ISpriteInstance {},
	ФонСундук: class extends self.ISpriteInstance {},
	Сундук: class extends self.ISpriteInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	Ключ: class extends self.ISpriteInstance {},
	КлючОдин: class extends self.ISpriteInstance {},
	ЗнакСундук: class extends self.ISpriteInstance {},
	Фонмагазин: class extends self.ISpriteInstance {},
	магазинфон: class extends self.ISpriteInstance {},
	Сундук3: class extends self.ISpriteInstance {},
	торговец: class extends self.ISpriteInstance {},
	Стол: class extends self.ISpriteInstance {},
	ДинамитМагазин: class extends self.ISpriteInstance {},
	Склянкамагазин: class extends self.ISpriteInstance {},
	Знакмагазин: class extends self.ISpriteInstance {},
	ТАЧ: class extends self.ISpriteInstance {},
	СундукЗначок: class extends self.ISpriteInstance {},
	МагазинЗначок: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	ДРАКОН: class extends self.ISpriteInstance {},
	Д: class extends self.ISpriteInstance {},
	Угли: class extends self.ISpriteInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	ГораЗолота: class extends self.ISpriteInstance {},
	Рабочий: class extends self.ISpriteInstance {},
	Склянка: class extends self.ISpriteInstance {},
	Динамит: class extends self.ISpriteInstance {},
	Цена: class extends self.ITextInstance {},
	Разъедание: class extends self.ISpriteInstance {},
	Взрыв: class extends self.ISpriteInstance {},
	КиркаДолбит: class extends self.ISpriteInstance {},
	маскаЗолота: class extends self.ISpriteInstance {},
	КоличествоКлючей: class extends self.ITextInstance {},
	Лут: class extends self.ISpriteInstance {},
	Лутбокс: class extends self.ISpriteInstance {},
	ПлюсГолда: class extends self.ITextInstance {},
	Спрайт7: class extends self.ISpriteInstance {},
	Спрайт8: class extends self.ISpriteInstance {},
	ФонКнопок: class extends self.ISpriteInstance {},
	Слова: class extends self.IArrayInstance {},
	AJAX: class extends self.IInstance {},
	Гномы: class extends self.ISpriteInstance {},
	Гоблины: class extends self.ISpriteInstance {},
	ФонДиалог: class extends self.ISpriteInstance {},
	СловаТекст: class extends self.ITextInstance {},
	ТехнДиалог: class extends self.ISpriteInstance {},
	Д2: class extends self.ISpriteInstance {},
	Биржа: class extends self.ISpriteInstance {},
	Камера: class extends self.ISpriteInstance {},
	Экран1: class extends self.ISpriteInstance {},
	Экран2: class extends self.ISpriteInstance {},
	БиржаМеню: class extends self.ISpriteInstance {},
	Спрайт9: class extends self.ISpriteInstance {},
	КнопкаКрасная: class extends self.ISpriteInstance {},
	КнопкаЗеленая: class extends self.ISpriteInstance {},
	Худ1: class extends self.ISpriteInstance {},
	Спот1: class extends self.ISpriteInstance {},
	ФонБиржа: class extends self.ISpriteInstance {},
	СтрелкаНазад: class extends self.ISpriteInstance {},
	Текст: class extends self.ITextInstance {},
	Купить: class extends self.ITextInstance {},
	Продать: class extends self.ITextInstance {},
	ТекстБиржа: class extends self.ITextInstance {},
	Спрайт10: class extends self.ISpriteInstance {},
	ВашСчет: class extends self.ITextInstance {},
	ВашБаланс: class extends self.ITextInstance {},
	ЦенаАкции: class extends self.ITextInstance {},
	фонпотеря: class extends self.ISpriteInstance {},
	Потеря: class extends self.ITextInstance {},
	Потеря2: class extends self.ITextInstance {},
	ЦенаАкции2: class extends self.ITextInstance {},
	потеряспот: class extends self.ISpriteInstance {},
	ВашБаланс2: class extends self.ITextInstance {},
	ЗолотоедСпавн: class extends self.ISpriteInstance {},
	Золотоед: class extends self.ISpriteInstance {},
	Спрайт11: class extends self.ISpriteInstance {},
	Свет: class extends self.ISpriteInstance {},
	ОбучалкаНачало: class extends self.ISpriteInstance {},
	Договор: class extends self.ISpriteInstance {},
	стрелкааним: class extends self.ISpriteInstance {},
	ДоговорБольшой: class extends self.ISpriteInstance {},
	Обводыч: class extends self.ISpriteInstance {},
	Стрелок: class extends self.ISpriteInstance {},
	ОбучалкаКлик: class extends self.ISpriteInstance {},
	обводкаинвентаря: class extends self.ISpriteInstance {},
	ОблачкоНетЗолота: class extends self.ISpriteInstance {},
	ОблачкоНетЗолота2: class extends self.ISpriteInstance {},
	ОписаниеПредметов: class extends self.ITextInstance {},
	Спрайт12: class extends self.ISpriteInstance {},
	Спрайт13: class extends self.ISpriteInstance {},
	обводкаинвентаря2: class extends self.ISpriteInstance {},
	обводкаинвентаря3: class extends self.ISpriteInstance {},
	КоличествоДинамита: class extends self.ITextInstance {},
	КоличествоСклянок: class extends self.ITextInstance {},
	КузницаПеред: class extends self.ISpriteInstance {},
	КузницаЗад: class extends self.ISpriteInstance {},
	Купить3: class extends self.ITextInstance {},
	Купить4: class extends self.ITextInstance {},
	Купить5: class extends self.ITextInstance {},
	Подпись: class extends self.ISpriteInstance {},
	ПОБЕДА: class extends self.ITextInstance {},
	СветПобеда: class extends self.ISpriteInstance {},
	ПОБЕДА2: class extends self.ITextInstance {},
	Ура: class extends self.ISpriteInstance {},
	Проигрыш: class extends self.ITextInstance {},
	мешок: class extends self.ISpriteInstance {},
	Спрайт15: class extends self.ISpriteInstance {},
	Спрайт16: class extends self.ISpriteInstance {},
	ТайловыйФон2: class extends self.ITiledBackgroundInstance {},
	Теньмешок: class extends self.ISpriteInstance {},
	ТайловыйФон3: class extends self.ITiledBackgroundInstance {},
	Экран3: class extends self.ISpriteInstance {},
	ФонМеню: class extends self.ISpriteInstance {},
	Спрайт17: class extends self.ISpriteInstance {},
	НазваниеИгры: class extends self.ISpriteInstance {},
	Спрайт19: class extends self.ISpriteInstance {},
	Язык: class extends self.ISpriteInstance {},
	Музыка: class extends self.ISpriteInstance {},
	Звук: class extends self.ISpriteInstance {},
	КнопкаИстория: class extends self.ISpriteInstance {},
	КнопкаСвободнаяИстория: class extends self.ISpriteInstance {},
	НазадСменю: class extends self.ISpriteInstance {},
	Руки1: class extends self.ISpriteInstance {},
	Руки2: class extends self.ISpriteInstance {},
	Руки3: class extends self.ISpriteInstance {},
	Блекскрин: class extends self.ISpriteInstance {},
	Спрайт14: class extends self.ISpriteInstance {},
	Заного: class extends self.ISpriteInstance {},
	ТриПолоски: class extends self.ISpriteInstance {},
	Кнопка1: class extends self.ISpriteInstance {},
	Кнопка2: class extends self.ISpriteInstance {},
	Кнопка3: class extends self.ISpriteInstance {},
	Кнопка4: class extends self.ISpriteInstance {},
	КнопкаТехн: class extends self.ISpriteInstance {},
	Текст2: class extends self.ITextInstance {},
	КнопкиМенюТекст: class extends self.ITextInstance {},
	ЛокальноеХранилище: class extends self.IInstance {},
	Удалить: class extends self.ISpriteInstance {},
	Аудио: class extends self.IInstance {},
	Спрайт18: class extends self.ISpriteInstance {},
	Тач2: class extends self.IInstance {},
	Гномик: class extends self.ISpriteInstance {},
	Квесты: class extends self.ITextInstance {},
	Прокачка: class extends self.ISpriteInstance {},
	Прокачка2: class extends self.ISpriteInstance {},
	КлючРеклама: class extends self.ISpriteInstance {},
	МобильнаяРеклама: class extends self.IInstance {},
	Палец: class extends self.ISpriteInstance {},
	Управлятор: class extends self.ISpriteInstance {},
	Светок: class extends self.ISpriteInstance {},
	ВзрывТриггер: class extends self.ISpriteInstance {},
	Рука: class extends self.ISpriteInstance {},
	РукаПоинт1: class extends self.ISpriteInstance {},
	РукаПоинт2: class extends self.ISpriteInstance {},
	Обучалка: class extends self.ISpriteInstance {},
	Спрайт20: class extends self.ISpriteInstance {},
	Спрайт21: class extends self.ISpriteInstance {},
	ПокупкиВПриложенияхIAP: class extends self.IInstance {},
	Монеты: class extends self.ISpriteInstance {},
	ХУД: class extends self.ISpriteInstance {},
	Диалог: class extends self.ISpriteInstance {},
	Спавн: class extends self.ISpriteInstance {},
	Поинтс: class extends self.ISpriteInstance {},
	Кнопки: class extends self.ISpriteInstance {},
	Звяки: class extends self.ISpriteInstance {},
	КузницаСлоты: class extends self.ISpriteInstance {},
	КнопкиЯзык: class extends self.ISpriteInstance {},
	КнопкиМеню: class extends self.ISpriteInstance {},
	НеТач: class extends self.ISpriteInstance {},
	НеМеню: class extends self.ISpriteInstance {}
}